### ISSUE TITLE
Counting words using TeXcount (Improvement)

### ISSUE THREAD

**Issue by hulk1st** [sharelatex/sharelatex#273] opened 2015-02-28 21:25 UTC
Hi,

I think the integration of TeXcount ( http://app.uio.no/ifi/texcount/ ) would be a nice improvement, since many conferences have a word limit when submitting an abstract. Unfortunately I'm not skilled enough to do so.

Cheers

**Comment by jpallen** [comment] 2015-03-04 09:15
+1

**Comment by henryoswald** [comment] 2015-06-08 18:04
duplicate of this https://github.com/sharelatex/web-sharelatex/issues/4

**Closed by henryoswald** 2015-06-08 18:04 UTC
