### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by sennierer** [sharelatex/sharelatex#265] opened 2015-02-16 15:21 UTC
Hi I am having a file upload issue with my self hosted sharelatex version. Small files are fine, but bigger pictures 150kb + upload not completely. I don't get an error, just the picture is only half etc. 
I already set the nginx file upload to 50mb as suggested in another similar issue...
Could it be something else?

**Comment by oxan** [comment] 2015-02-16 18:48
I'm experiencing this issue as well.

**Comment by jpallen** [comment] 2015-02-17 10:25
Can you post the logs from the web and filestore services from during the upload please? Also, how have you installed ShareLaTeX?

**Comment by sennierer** [comment] 2015-02-17 10:54
Thanks for your fast reply.
I installed it the from github (not the docker image), the newest version three days ago. I run it on a debian wheezy machine (7.8). I have to say that due to a apache already running on the machine I use nginx to serve sharelatex on port 5000 to the apache server. Not very elegant I know, but everything else but the file upload seem to work fine.

Here is the filestore.log:
```
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"reciving request to insert file","time":"2015-02-17T10:38:19.517Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"location":"/var/lib/sharelatex/data/user_files","target":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","msg":"sending file stream","time":"2015-02-17T10:38:19.518Z","v":0}
/var/lib/sharelatex/tmp/uploads 16b129e0-b691-11e4-9662-0367e66382c9
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/16b129e0-b691-11e4-9662-0367e66382c9","msg":"writing file locally","time":"2015-02-17T10:38:19.518Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"fsPath":"/var/lib/sharelatex/tmp/uploads/16b129e0-b691-11e4-9662-0367e66382c9","msg":"finished writing file locally","time":"2015-02-17T10:38:19.521Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"location":"/var/lib/sharelatex/data/user_files","target":"54e317cd7b38d78a10cbaef3_54e31a1b7b38d78a10cbaefc","source":"/var/lib/sharelatex/tmp/uploads/16b129e0-b691-11e4-9662-0367e66382c9","msg":"sending file","time":"2015-02-17T10:38:19.521Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/file/54e31a1b7b38d78a10cbaefc","method":"POST","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":5,"msg":"http request","time":"2015-02-17T10:38:19.522Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"reciving request to get file","time":"2015-02-17T10:38:22.127Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"bucket":"/var/lib/sharelatex/data/user_files","key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","opts":{},"msg":"getting file","time":"2015-02-17T10:38:22.127Z","v":0}
{"name":"54e317cd7b38d78a10cbaef3_54e31a1b7b38d78a10cbaefc","hostname":"senserve","pid":4330,"level":30,"location":"/var/lib/sharelatex/data/user_files","msg":"getting file","time":"2015-02-17T10:38:22.127Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.128Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.129Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.129Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.130Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.131Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"key":"54e317cd7b38d78a10cbaef3/54e31a1b7b38d78a10cbaefc","bucket":"/var/lib/sharelatex/data/user_files","msg":"sending file to response","time":"2015-02-17T10:38:22.132Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/file/54e31a1b7b38d78a10cbaefc","method":"GET","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":200},"response-time":6,"msg":"http request","time":"2015-02-17T10:38:22.133Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/file/54e31a1b7b38d78a10cbaefc","method":"GET","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":200},"response-time":7,"msg":"http request","time":"2015-02-17T10:38:22.134Z","v":0}
{"name":"filestore","hostname":"senserve","pid":4330,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/file/54e31a1b7b38d78a10cbaefc","method":"GET","remote-addr":"127.0.0.1","content-length":"0"},"res":{"statusCode":200},"response-time":7,"msg":"http request","time":"2015-02-17T10:38:22.134Z","v":0}
```

and here the web.log:
```
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"folder_id":"54e317cd7b38d78a10cbaef4","project_id":"54e317cd7b38d78a10cbaef3","msg":"confirming folder in project","time":"2015-02-17T10:38:19.513Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","file_id":"54e31a1b7b38d78a10cbaefc","fsPath":"/var/lib/sharelatex/tmp/uploads/1faba7d624e0149dc60ee6ef1f430a73","msg":"uploading file from disk","time":"2015-02-17T10:38:19.513Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query":{"_id":"54e317cd7b38d78a10cbaef3"},"query_type":"query","collection":"sharelatex.projects","response-time":10,"msg":"mongo request","time":"2015-02-17T10:38:19.532Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","element_id":"54e31a1b7b38d78a10cbaefc","fileType":"fileRefs","folder_id":"54e317cd7b38d78a10cbaef4","msg":"adding element to project","time":"2015-02-17T10:38:19.534Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query_type":"update","collection":"sharelatex.projects","response-time":2,"msg":"mongo request","time":"2015-02-17T10:38:19.537Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query":{"_id":"54e317cd7b38d78a10cbaef3"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-02-17T10:38:19.538Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","user_id":"54e0f8d5e379d3742f3f273d","path":"/scientific-excellency-sustainability/chart_2-01.png","rev":0,"msg":"sending file to third party data store","time":"2015-02-17T10:38:19.538Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","user_id":"54e0f8d5e379d3742f3f273d","path":"/scientific-excellency-sustainability/chart_2-01.png","rev":0,"msg":"sending file to third party data store queued up for processing","time":"2015-02-17T10:38:19.539Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","file_path":"/var/lib/sharelatex/tmp/uploads/1faba7d624e0149dc60ee6ef1f430a73","file_name":"chart_2-01.png","folder_id":"54e317cd7b38d78a10cbaef4","msg":"uploaded file","time":"2015-02-17T10:38:19.540Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/upload?folder_id=54e317cd7b38d78a10cbaef4&_csrf=_vHbenzrEkwQEQ7ZCoU8Qr42&qquuid=1ec7d5bb-dfc4-49f2-abc6-c0d2ced1fa6e&qqtotalfilesize=387423","method":"POST","referrer":"http://latex.schloegl.net/project/54e317cd7b38d78a10cbaef3","remote-addr":"80.110.36.179","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18","content-length":"387612"},"res":{"statusCode":200},"response-time":56,"msg":"http request","time":"2015-02-17T10:38:19.540Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query":{"_id":"54e317cd7b38d78a10cbaef3"},"query_type":"query","collection":"sharelatex.projects","response-time":1,"msg":"mongo request","time":"2015-02-17T10:38:22.111Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query":{"_id":"54e0f8d5e379d3742f3f273d"},"query_type":"query","collection":"sharelatex.users","response-time":1,"msg":"mongo request","time":"2015-02-17T10:38:22.112Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"user":{"id":"54e0f8d5e379d3742f3f273d","email":"matthias@schloegl.net"},"project":{"id":"54e317cd7b38d78a10cbaef3","name":"future_earth"},"msg":"Checking if can access","time":"2015-02-17T10:38:22.112Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","file_id":"54e31a1b7b38d78a10cbaefc","queryString":{},"msg":"file download","time":"2015-02-17T10:38:22.112Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"query":{"_id":"54e317cd7b38d78a10cbaef3"},"query_type":"query","collection":"sharelatex.projects","response-time":10,"msg":"mongo request","time":"2015-02-17T10:38:22.123Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"project_id":"54e317cd7b38d78a10cbaef3","file_id":"54e31a1b7b38d78a10cbaefc","query":{},"msg":"getting file stream from file store","time":"2015-02-17T10:38:22.125Z","v":0}
{"name":"web-sharelatex","hostname":"senserve","pid":4234,"level":30,"req":{"url":"/project/54e317cd7b38d78a10cbaef3/file/54e31a1b7b38d78a10cbaefc","method":"GET","referrer":"http://latex.schloegl.net/project/54e317cd7b38d78a10cbaef3","remote-addr":"80.110.36.179","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18"},"res":{"statusCode":200},"response-time":25,"msg":"http request","time":"2015-02-17T10:38:22.135Z","v":0}
```

Thanks very much for your help!

**Comment by jpallen** [comment] 2015-02-18 12:03
Nothing looks wrong in the logs. Can you look in /var/lib/sharelatex/data/user_files and see if the file has uploaded there correctly please? Does the image include ok if you compile it in a document?

**Comment by sennierer** [comment] 2015-02-18 14:06
This is strange. While the png file looks corrupted in sharelatex (only half of the png is shown, when clicking on it in the web interface) and the latex-file does not compile (complaining about a corrupted png file) it is stored fine in the user_files directory. And I checked that again: this happens only with larger 100+kb image files (I tested png & jpg).

**Comment by jpallen** [comment] 2015-02-18 14:14
Can you check that your Nginx/reverse proxy is set up ok to serve large
files? I'm not sure what options these would be exactly though, sorry.

Regards,
James

**Comment by sennierer** [comment] 2015-02-18 14:14
That is the compile error from the latex compiler:
```[17 </var/lib/sharelatex/data/compiles/54e225972c4127e724fad50f/charts/chart_2.
png
!pdfTeX error: pdflatex: libpng: internal error
 ==> Fatal error occurred, no output PDF file produced!```

And it is interesting that in the compile folder the original png file is nearly 4 times as big as the original png:
original png: ```-rw-r--r-- 1 sharelatex sharelatex 387423 Feb 17 11:38 54e317cd7b38d78a10cbaef3_54e31a1b7b38d78a10cbaefc```

the one in the compile folder: ```-rw-r--r-- 1 sharelatex sharelatex 1341498 Feb 18 15:07 chart_2.png```

**Comment by sennierer** [comment] 2015-02-18 14:16
As there is a compile error from latex and the upload is fine I don't think that this is an nginx issue.

However, I have ```client_max_body_size 50M;``` set in the nginx conf.

**Comment by jpallen** [comment] 2015-02-18 14:21
Can you check what sort of content those files have. Are they actually image files, or is something else strange going on?

**Comment by sennierer** [comment] 2015-02-18 14:28
That was actually the first thing I checked. These are png files produced in Adobe creative suit 5.5 on a Mac. I used them on my local LaTex compiler without a problem. However, I reexported them from AI and I am still experiencing the same problem.
See the following screenshot, looks like they were not uploaded completely (the smaller ones show fine), but the are complete on the server.

![screenshot](https://cloud.githubusercontent.com/assets/499265/6248703/a447e1ee-b782-11e4-9e50-d3dbbcd09881.png)

**Comment by jpallen** [comment] 2015-02-18 14:30
So the file in the user_files directory is correct? In this case the upload has worked ok, so it must be something to do with serving the file. What happens if you open the image in the compile folder? Is that incomplete in the same way as in the editor?

**Comment by sennierer** [comment] 2015-02-18 14:30
Another thing: when I click on download, I get the corrupted image that is 1.3 mb big instead of the 387kb my uploaded file had....just as the file I found in the compile folder (comment above).

**Comment by sennierer** [comment] 2015-02-18 14:32
Yes it is...and strangely 4 times as big as the original one.

**Comment by jpallen** [comment] 2015-02-18 14:34
Which version of Node are you running on? I think I see a possible cause for this.

**Comment by jpallen** [comment] 2015-02-18 14:36
I think the problem is that the event at https://github.com/sharelatex/filestore-sharelatex/blob/master/app/coffee/FSPersistorManager.coffee#L40 is emitted each time there is new data to read from the file, not just once. The callback is called multiple times and the stream is piped into the response multiple times, duplicating the data and corrupting the image.

**Comment by sennierer** [comment] 2015-02-18 14:37
0.10.29 from the debian backports.

**Comment by sennierer** [comment] 2015-02-18 14:42
Ok I'll try and compile the latest version of node myself.

**Comment by jpallen** [comment] 2015-02-18 14:55
Sorry if I wasn't clear, but I don't think this is todo with the Node version. There is a bug in our code which needs fixing here.

**Comment by oxan** [comment] 2015-02-24 15:44
If I replace the `readable` event with the `open` event in https://github.com/sharelatex/filestore-sharelatex/blob/master/app/coffee/FSPersistorManager.coffee#L40, the problem indeed disappears (after clearing the relevant caches). Not sure whether that's the correct fix though.

**Comment by jpallen** [comment] 2015-02-26 11:34
This is fixed in sharelatex/filestore-sharelatex@aa6f61bbf9a5840a8d324062a6cff2406ab2cdfd and will be released as 0.1.3 later on today.

**Closed by jpallen** 2015-02-26 11:34 UTC

**Comment by DamianoP** [comment] 2021-08-12 12:10
> Can you check that your Nginx/reverse proxy is set up ok to serve large
> files? I'm not sure what options these would be exactly though, sorry.
> 
> Regards,
> James
> 
> On Wed, Feb 18, 2015 at 2:06 PM, sennierer [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > This is strange. While the png file looks corrupted in sharelatex (only
> > half of the png is shown, when clicking on it in the web interface) and the
> > latex-file does not compile (complaining about a corrupted png file) it is
> > stored fine in the user_files directory. And I checked that again: this
> > happens only with larger 100+kb image files (I tested png & jpg).
> > —
> > Reply to this email directly or view it on GitHub
> > [#265 (comment)](https://github.com/overleaf/overleaf/issues/265#issuecomment-74868472)
> > .

Ty, you solved my problem !!!

**Comment by mathklk** [comment] 2026-04-27 17:08
The original issue seems to have been a problem in overleaf, but I got the same "Upload Error" due to a bad nginx conf.
If you don't specify a body size limit in nginx, it will default to 1 megabyte. With high resolution images it's easy to pass this limit.

As already pointed out in this thread, you can adjust the limit with the `client_max_body_size` property in your nginx config.
```
# disable limit entirely
client_max_body_size 0;

# set limit to 20 MB
client_max_body_size 20m;
```
